stages:
  preprocess:
    cmd: python src/data/preprocess.py --input ./data/external/dataset.csv
    deps:
    - data/external/dataset.csv
    - src/data/preprocess.py
    outs:
    - data/preprocessed
  featurization:
    cmd: python src/features/featurize.py --input ./data/preprocessed/preprocessed_dataset.csv
    deps:
    - data/preprocessed/preprocessed_dataset.csv
    - src/features/featurize.py
    params:
    - featurization.truncatedSVD_number_of_components
    outs:
    - data/featurized
  split:
    cmd: python src/splits/split_train_test.py --features ./data/featurized/featurized_dataset.npz
    deps:
    - data/featurized/featurized_dataset.npz
    - src/splits/split_train_test.py
    params:
    - split.train_percentage
    outs:
    - data/processed
  training:
    cmd: python src/models/train_model.py --train_data ./data/processed/train_dataset.npz
    deps:
    - data/processed/train_dataset.npz
    - src/models/train_model.py
    outs:
    - models
  evaluation:
    cmd: python src/evaluation/evaluate.py --test_data data/processed/test_dataset.npz
      --model models/linear_regression.joblib
    deps:
    - data/processed/test_dataset.npz
    - models/linear_regression.joblib
    - src/evaluation/evaluate.py
    metrics:
    - reports/scores.json:
        cache: false
    plots:
    - reports/predictions.json:
        cache: false
