stages:
  preprocess:
    cmd: python src/data/preprocess.py --input ./data/external/dataset.csv
    deps:
    - data/external/dataset.csv
    - src/data/preprocess.py
    outs:
    - data/preprocessed
  featurization:
    cmd: python src/features/featurize.py --input ./data/preprocessed/preprocessed_dataset.csv
    deps:
    - data/preprocessed/preprocessed_dataset.csv
    - src/features/featurize.py
    params:
    - featurization.truncatedSVD_number_of_components
    outs:
    - data/featurized
  split:
    cmd: python src/splits/split_train_test.py --features ./data/featurized/featurized_dataset.npz
    deps:
    - data/featurized/featurized_dataset.npz
    - src/splits/split_train_test.py
    params:
    - split.train_percentage
    outs:
    - data/processed
