stages:
  preprocess:
    cmd: python src/data/preprocess.py --input ./data/external/dataset.csv
    deps:
    - data/external/dataset.csv
    - src/data/preprocess.py
    outs:
    - data/preprocessed
  featurization:
    cmd: python src/features/featurize.py --input ./data/preprocessed/preprocessed_dataset.csv
    deps:
    - data/preprocessed/preprocessed_dataset.csv
    - src/features/featurize.py
    params:
    - featurization.truncatedSVD_number_of_components
    outs:
    - data/featurized
